### ISSUE TITLE
Misplaced intermissions

### ISSUE THREAD

**Issue by AlWesker** [maxim-zhao/battlemaniacs-restoration#12]
The last release added the intermissions and they look great (even though the T Bird artwork got an update to remove the brown shade of the mouth that looked like a chocolate stain, please change it to the last updated version) and the randomed message work perfect too. But from the snake levels on, the intermissions are misplaced and this causes issues further on in the game. The snake levels don't need intermissions between themselves because those were an unified level in the SNES version, but the Master System version consider them as separate levels. Since the intermissions are showing before they should, when you get to level nine you get the ending intermisison beforehand and the game glitches, and then the game shows glitched intermissions between levels.

According to how the game is structured, this is how the intermission sequence has to go.

Level One (Ragnarok Canyon) end with Intermissions 1
Level Two (Hollow Tree) end with Intermissions 2
Level Three (Bonus Level 1) end with Intermissions 3
Level Four (Turbo Tunnel) end with Intermissions 4
Level Five (Snake Pit 1)
Level Six (Snake Pit 2)
Level Seven (Snake Pit 3)
Level Eight (Snake Pit 4) end with Intermissions 5
Level Nine (Bonus Level 2) end with Intermissions 6
Level Ten (Roller Coaster) end with Intermissions 7
Level Eleven (Dark Tower) end with Intermisisons 8
Level Twelve (Dark Queen final boss) end with Intermissions 9 or the Intermissions that go prior to ending

**Comment by maxim-zhao** [comment]
I wasn't able to play though to judge this. I'm using the level number in RAM, so I just need to insert some blank entries in positions 5-7.

**Comment by maxim-zhao** [comment]
This should be fixed in the most recent draft (20180726a) - can you confirm?

**Comment by AlWesker** [comment]
It's perfect now. Thanks.

A little issue I just noticed with the script text. In the second bonus level, the text says "DOMINOES" in at least two T Bird instances, but I forgot that actually the second bonus level in the Master System version doesn't use the dominoes that were present in the SNES version, it rather reuses the same bowling pins of the first bonus level. Is it very complicated to change now those two "DOMINOES" instances by "PINS"? If It's too much work, then leave them as "DOMINOES". Whatever you do, please close the issue after that.

**Comment by maxim-zhao** [comment]
You should really look at the source file - changing text is totally trivial
