### ISSUE TITLE
Logo for the title screen

### ISSUE THREAD

**Issue by AlWesker** [maxim-zhao/battlemaniacs-restoration#17]
So, given this game has two different logos (a "Battlemaniacs" logo on the SNES title screen and a "Battletoads in Battlemaniacs" logo on the SNES boxart), question is which one we should use as standard hack logo and maybe leave the other one for a possible optional patch to make everyone happy.

The "Battlemaniacs" logo from the SNES title screen.

![imagen](https://user-images.githubusercontent.com/41370804/43672318-d27ba2aa-97ab-11e8-873f-07106d0c2e0e.png)

And two adapted versions of the "Battletoads in Battlemaniacs" logo from the SNES boxart:

![imagen](https://user-images.githubusercontent.com/41370804/43672321-dd2731c4-97ab-11e8-99b4-67dba2b57576.png)

![imagen](https://user-images.githubusercontent.com/41370804/43672322-e548cd5e-97ab-11e8-8838-374ee64d88a1.png)

Regarding the two Battletoads in Battlemaniacs logos, one uses a SNES Battletoads logo (from Battletoads Double Dragon) as a basis while the other uses a NES Battletoads logo (from Battletoads). I like the SNES one more, it stands out much more and the Master System seem to be able to handle it. Pyron, on the other hand, likes the NES Battletoads logo more, although I think it's looking rather limited for what a Master System can offer color/palette wise. It would be good for a NES version, but I think a Master System version can benefit much more for the another one which has been well converted by Pyron anyway.

And comparing any of the Battletoads in Battlemaniacs logo with the simpler Battlemaniacs logo, maybe it may seem that the simpler Battlemaniacs logo is a better choice, but it's incomplete. It would need a simple "Battletoads in" letter appendix on top of it maybe (I think the "Presents Zitz, Rash, and Pimple as the Battletoads in" in the preceding screen doesn't convince me, we are probably going to return to the original "Presents Zitz, Rash, and Pimple in" with that one). The "Battletoads in Battlemaniacs" logo solves that problem, but maybe isn't as fancy looking.

Even if one of these possible logos is chosen as standard, I think the other one s shouldn't be discarded but be offered as optional small patches, so everyone is happy that way.

**Comment by PyronsLair** [comment]
Hard question..
If you gonna follow to be faithfull to the original game we must follow the original logo.

But i think that battlemaniacs logo is a mistake and the correct of course as "battletoads logo" + "battlemaniacs" a did alot of other versions. Someone may fit well

**Comment by maxim-zhao** [comment]
I'm going to leave it up to you guys - the current and SNES logos both fail to mention Battletoads, but is the goal here to polish the port to be closer to the SNES version, or to make it the way you wish it was? I find the "in Battlemaniacs" overlay to be quite ugly, the box art it's based on seems like it was done in a hurry because they wanted to have the Battletoads logo on the box. Compare to the SMS box art: http://www.smspower.org/uploads/Scans/Battlemaniacs-SMS-BR.jpg which doesn't try to work around it. So, is it Battlemaniacs or Battletoads in Battlemaniacs? I prefer the former.

**Comment by PyronsLair** [comment]
I have spoke with wesker about it before, i think the snes box art its a pre rendered crap. But for another side.. everyones taht i know includes me know this game as "battletoads in Battlemaniacs" i always think that changes the logo to just "battlemaniacs seens out of the place.

Also.. every other game in the series is called Battletoads + subtitle. 

But i'm not the game designer behind of it, so because it i mention before if is to be faithfull we must use "Battlemaniacs logo" also its dosen't look bad either.

In the end for me the choice depends of how you gonna lead the project, any decision is fine for me.

**Comment by AlWesker** [comment]
The Brazilian SMS box art was a quick job done by TecToy. I bet Virgin would have used the SNES boxart and logo for the European SMS release but that's just theorizing as it was never shown in any magazine advert. It's obvious that the SNES boxart logo was a post-game decision and hence the inconsistency with the SNES screen title logo which seems like the initial design by RARE.

But the title of the game, or at least on the SNES, is definitely "Battletoads in Battlemaniacs". It's even that way on the SNES presentation, even if it's just not referenced as visually as the boxart. But you can notice the intro screen goes with "Battletoads" "in" "Battlemaniacs" in different frames, with "Battletoads" and "in" being simpler texts using the game font and then "Battlemaniacs" being the title screen logo. 

![imagen](https://user-images.githubusercontent.com/41370804/43672345-5848abbc-97ac-11e8-87ae-c31ef2e703d2.png)

![imagen](https://user-images.githubusercontent.com/41370804/43672346-5f5c0e1c-97ac-11e8-98bb-3b9764ae1f07.png)

![imagen](https://user-images.githubusercontent.com/41370804/43672349-72380bbc-97ac-11e8-9d8c-fbb2e2ec7677.png)

The problem is, the Master System version omitted those "Battletoads" "in" parts of the presentation and just went with "Present Zitz, Rash & Pimple in" "Battlemaniacs", hence why the title of the game/ROM dumps and such on the Master System version are always simplified to "Battlemaniacs" and why in the case of the SNES version, you hardly see the game referenced through the simpler "Battlemaniacs" but rather by the full "Battletoads in Battlemaniacs". It's like that on official entries and listings, on ROM dumps and else.

So OK, we are using the SNES Battlemaniacs logo of the title screen for fitting the SNES version better but then we should also have the "Battletoads" "In" part added in somehow, even if it's just simpler text like the SNES version does. Right now it says "Presents Zitz, Rash & Pimple as the Battletoads in", but doesn't convince me, it doesn't stand out that much as a game title. Maybe we should add a simple "Battletoads in" text (using the text font the title screen is going to use) on top of the Battlemaniacs logo then?

And in case of these "Battletoads in Battlemaniacs" logos adapted from the boxart, I still think at least one of them should be offered as an optional patch as there may be people who prefer this sort of title screen logo. Maybe even the transparent one you did Pyron, if you really like that, although I'm more fond of the one which uses the SNES Battletoads logo variant.

**Comment by PyronsLair** [comment]
We have space and tile count to include "battletoads in.." i can draw it
later i do some samples if you guys agree with it.

2018-07-31 18:03 GMT-03:00 Albert Wesker <notifications@github.com>:

**Comment by AlWesker** [comment]
Some lousy and quick attempt I just did with the current title screen hack (we would need to add the starfield background).

![imagen](https://user-images.githubusercontent.com/41370804/43672354-8538bacc-97ac-11e8-81f5-d9232a7527a7.png)

That's the idea. Imagine that in the first "Restoration" it says "Battletoads", lol.

**Comment by maxim-zhao** [comment]
It'd be no big deal to "flash" the "Battletoads in" text in the same way as the SNES version, it's just extra pages in the script (although we don't have any palette fading). I think having it burned into the title screen is the way it should always have been, but for me the "Battletoads in" serves as an optional prefix to the real game title, just like "Castle of Illusion (starring Mickey Mouse)" has a suffix.

**Comment by AlWesker** [comment]
Maybe you are right, plus adding script pages without a palette fading is going to be odd and that would make for a lot of unnecessary screens. There's a lot of them already with the two copyright screens, the Virgin logo and the "Present Zitz, Rash and Pimple in". So go ahead with burning the "Battletoads in" fragment on top of the Battlemaniacs logo on the title screen. The "Battletoads in Battlemaniacs" logo adaptation from the boxart logo will be kept as an optional title screen patch/mod for anyone that wishes that one.

Now that you are mentioning the "Castle of Illusion starring Mickey Mouse", it may be a similar case. Obviously people are going to tell you "Castle of Illusion" to minimize/not telling you so much words, but in the end, the full official title of the game is "Castle of Illusion starring Mickey Mouse" and it's shown as such in the boxart, the title screen, the official entries and else. It's the same with "Battletoads in Battlemaniacs". People will tell "Battlemaniacs" to minimize, but in the end, it's a proven aspect that the full title is "Battletoads in Battlemaniacs", as it goes on the official entries of the game (at least those of the SNES version).

**Comment by maxim-zhao** [comment]
Note that the entire pre-title screen sequence is skippable now - the original had the first three unskippable. So adding a couple of screens won't matter much.

**Comment by maxim-zhao** [comment]
Intro sequence now shows:
![image](https://user-images.githubusercontent.com/7792986/43808443-f73ccb4a-9aa4-11e8-979c-78072706d791.png)
![image](https://user-images.githubusercontent.com/7792986/43808422-e4df9b80-9aa4-11e8-8317-c36158f10b15.png)
![image](https://user-images.githubusercontent.com/7792986/43808453-fd75fb80-9aa4-11e8-8d7b-61d2dc0af30c.png)
I think we can close this one now.

**Comment by PyronsLair** [comment]
I vote for restoration text with a cooler font

Em ter, 7 de ago de 2018 20:50, Maxim <notifications@github.com> escreveu:

**Comment by AlWesker** [comment]
For some reason I prefer it minimalistic, like it's now. Otherwise it would take a good chunk of space for the rest of title screen elements and I believe it's ok right now, as that's more like a apendix (indicating this is a hack) rather than part of the real title of the game.

**Comment by AlWesker** [comment]
hose pre-title screen texts look much, much better now. Well done.

For some reason I prefer the Restoration bit kept minimalistic, like it's now. Otherwise it would take a good chunk of space (no pun intended) for the rest of title screen elements and I believe it already looks well enough, as that Restoration part is more like a appendix (indicating this is a hack) rather than part of the real title of the game.

**Comment by AlWesker** [comment]
Those pre-title screen texts look much, much better now. Well done.

For some reason I prefer the Restoration bit kept minimalistic, like it's now. Otherwise it would take a good chunk of space (no pun intended) for the rest of title screen elements and I believe it already looks well enough, as that Restoration part is more like a appendix (indicating this is a hack) rather than part of the real title of the game.
