### ISSUE TITLE
Pre-title sequence with starfield

### ISSUE THREAD

**Issue by maxim-zhao** [maxim-zhao/battlemaniacs-restoration#19]
I've made a version of the intro sequence which is entirely bitmapped. With some tricks this means we have a single "legals" screen, stars throughout (not moving), and the title screen is mostly done (apart from the bottom line of text). Can you give some feedback?

**Comment by PyronsLair** [comment]
The intro I will finish later,  I stopped to do the char select screen.
But it gonna spend a lot of time,  so have patience.

Em ter, 7 de ago de 2018 20:43, Maxim <notifications@github.com> escreveu:

**Comment by AlWesker** [comment]
The pre-title sequence with copyrights, Virgin, Zitz, Rash, Pimple and else, as such is perfect now.

There's an issue which is generated by the new version but it doesn't cover the pre-title sequence with the starfield. I think I should open another issue for that as that deals with the continue and game over intermissions.

**Comment by maxim-zhao** [comment]
I think I'm happy with it, closing.
