### ISSUE TITLE
Intermissions for Continue and Game Over sequences

### ISSUE THREAD

**Issue by AlWesker** [maxim-zhao/battlemaniacs-restoration#20]
The last version has the Game Over intermissions, which are the ones which follow the same pattern of the level intermissions in which the Dark Queen "asks" and Professor T. Bird "answers", swapped in place of where the Continue intermissions should be, which is just Professor T. Bird taunting you (for example, one of them is the one that says "I can't believe what's happening! Even I could have blablabla"). I believe that was ok in the previous version. 

There's two possible patterns that could be set for this. One that uses the basis of the Master System version patten (which had a single Continue intermission and no Game Over intermission) but expanding it with the rest of the SNES pattern, and one that mimicks the SNES version. Any of both would be fine, we just would have to agree which one is best or which one would be easier to implement.

The Master System+SNES version pattern would be like this. When you die your last life, there should appear one out of four (picked at random) Continue intermission screens with the Professor T. Bird taunting you, and then follows the Continue screen with the countdown. If you continue the game, nothing else happens and then you resume the game. If you don't continue the game (or in case you get a Game Over due running out of continues), then it would follow one out of four (picked at random) Game Over intermissions with the Dark Queen "asking" and the "Professor T. Bird "answering", and then the game would reset. See how the Master System version works (but add the Game Over intermissions after having a Game Over, instead of skipping stright to reseting the game) in these videos:

Continuing the game

https://www.youtube.com/watch?v=vQATCGJJ7SA (see 3:05)

Getting a Game Over

https://www.youtube.com/watch?v=aFAs3pmeyDU

The SNES version pattern would be like this. When you die your last life, there should appear the Continue screen with the countdown. If you continue the game, one out of four (picked at random) Continue intermission screens with the Professor T. Bird taunting you, and then you resume the game. If you don't continue the game (or in case you get a Game Over due running out of continues), then it would follow one out of four (picked at random) Game Over intermissions with the Dark Queen "asking" and the "Professor T. Bird "answering", and then the game would reset. See how the SNES version works in these videos:

Continuing the game

 https://www.youtube.com/watch?v=U8zamvkZnW8 (see 10:17)

Getting a Game Over

https://www.youtube.com/watch?v=SLZS3fUg06g

In this comparative video of the Master System and SNES version you can also see (at 7:55) how both version work when you enter the Continue screen and decide not to continue. These ones also show the transition to reseting the game in both versions.

https://www.youtube.com/watch?v=Q0fsKHiAfBA

**Comment by maxim-zhao** [comment]
I'd assumed we would always have one of the game over intermissions when you die, then a continue intermission if you continue, but it makes more sense to only see one of them depending on whether you continue. Can you fix the link to the SNES continue sequence?

**Comment by AlWesker** [comment]
My bad. It's fixed now.

So I guess we are replicating the SNES version then. That would make no intermission appearing between running out of lives and getting the Continue/Game Over screen, like you can see in the SNES videos. The continue intermissions would appear in case you continue, and the Game Over intermissions in case you don't continue or run out of continues.

**Comment by maxim-zhao** [comment]
It makes sense to me.

**Comment by maxim-zhao** [comment]
This is now fixed.
