### ISSUE TITLE
Title screen music

### ISSUE THREAD

**Issue by AlWesker** [maxim-zhao/battlemaniacs-restoration#21]
Right now, the title screen lacks any music. You only get it if you come from a Game Over and it's because the Game Over screen triggers the title screen music, but at boot you don't get anything.

The original Master System version had the approach of loading the title screen music when the title screen appears (so the pre-title copyright screens are silent) and if you let the game loop the intro and back to the copyright and title screens, it would reset the music in the title screen. You can see it here.

https://www.youtube.com/watch?v=pIXDlv9y8AQ

I wonder if this approach can be changed. Basically, making the game not reseting the title screen music when it goes on a loop and goes back to the title screen after coming from the intro. I feel reseting the title screen music there hampers the music, it would be much better if all the demo sequence would be left with the music uninterrupted no matter how many times the game loops to the title screen. You can see this approach on Battletoads Double Dragon for the Mega Drive.

https://www.youtube.com/watch?v=brE-TiwZpo8 (see from the beginning and until 2:49)

Also, the SNES version of Battletoads in Battlemaniacs actually starts the music playing during the pre-title screens and before the title screen appear. Only the Tradewest logo is silenced. But this is because in the SNES version that screen is static and then the music starts playing when there's some movement on the screen (which the Master System version lacks) so maybe in our case the music could start playing at boot.

https://www.youtube.com/watch?v=jRioxNkfM4I

So, what do you guys think? Making the title screen music starts playing at boot or when the title screen shows the first time? And making the title screen music being restarted in the title screen like the Master System version does or letting it continue uninterrupted?

**Comment by maxim-zhao** [comment]
I haven't been testing with audio on, which is why the music went missing. It's easy to fix. If I start the music right at the start then it will not restart during the intro loop, which I think is good.

**Comment by AlWesker** [comment]
Great. Add it right at the start then.
