### ISSUE TITLE
looping vgm problem

### ISSUE THREAD

**Issue by MotavianRaider** [maxim-zhao/battlemaniacs-restoration#24]
Hi, sorry for holding everyone up, I've been preoccupied with other music related things. I finished the rollercoaster track but when I tried to convert it to looped vgm with vgmtrim it couldn't open the file. I logged the vgm with sneventracker. Does anyone know what I'm doing wrong? Its my first time doing something like this. Thanks.

![help](https://user-images.githubusercontent.com/41930941/44010565-dae4ccd6-9e78-11e8-8bb4-982eeebfde23.png)

**Comment by MotavianRaider** [comment]
I have discovered the issue is the way Sneventracker logs vgms. Its absolutely asinine to the point where I've decided to port the song over to Deflemask. From this point all of the songs w
ill be created from there.

**Comment by maxim-zhao** [comment]
I spent some time sorting out the existing ones. Sneventracker simply logs the chip commands as it plays, the same as dumping a VGM from an emulator and thus requires more work from you - you have to play through a few loops if you want to get it trimmed automatically, else you have to find your trimming times laboriously. If you're happy to switch to another tracker then that simplifies things.
