### ISSUE TITLE
Redrawn artwork for ending

### ISSUE THREAD

**Issue by maxim-zhao** [maxim-zhao/battlemaniacs-restoration#27]
The ending artwork is all placeholders. This is in addition to #14.

**Comment by PyronsLair** [comment]
I'm busy these days but i will finish it soon

Em qua, 29 de ago de 2018 às 06:05, Maxim <notifications@github.com>
escreveu:

**Comment by maxim-zhao** [comment]
I think this is all done now, can we close this one?
