### ISSUE TITLE
Pause music

### ISSUE THREAD

**Issue by AlWesker** [maxim-zhao/battlemaniacs-restoration#30]
The SNES version has a small jingle played when the game is paused, similar to the famous "toad rap" of the NES version of Battletoads.

https://www.youtube.com/watch?v=JlO9V8wPVx8

Would it be possible to implement it? Even if it's a very short tune, it's best to know if it can be added (I don't know what the Master System version does when pausing) before telling @sanchez-david if he has to do it or not.

**Comment by maxim-zhao** [comment]
Yes, I've implemented it now so please make some music to play there...

**Comment by AlWesker** [comment]
Done and uploaded now. Please close this when you implement it.
