### ISSUE TITLE
T. Bird text field is cut

### ISSUE THREAD

**Issue by AlWesker** [maxim-zhao/battlemaniacs-restoration#31]
For some reason, the text field of the T. Bird image in the intermission appears cut. I remember this appeared right at first, but since I don't know which revision of the hack, it now appears cut. Here's an example of how it appears now.

![Battletoads in Battlemaniacs (Brazil) (Restoration Hack) (Beta)-12](https://user-images.githubusercontent.com/41370804/55048979-8626c300-504a-11e9-9234-7153c03e3eb1.png)

And this is how it appeared before and how it should.

![Battletoads in Battlemaniacs (Brazil) (Restoration Hack) (Beta)-09](https://user-images.githubusercontent.com/41370804/55048991-92ab1b80-504a-11e9-86cd-21f36a63c889.png)

So, what's exactly the issue here?

**Comment by maxim-zhao** [comment]
This seems to be only on the continuous build - it works for for me locally. I haven't been able to figure out why it is behaving differently yet.

**Comment by maxim-zhao** [comment]
It seems it was a bug/incompatibility in the ZX7 compressor, which was omitting the last part of the picture when it was loaded - the text was never overwriting it. I've amended the build process to pick up a newer version of that compressor and it seems OK now.

**Comment by AlWesker** [comment]
Great!
