### ISSUE TITLE
More music needed

### ISSUE THREAD

**Issue by maxim-zhao** [maxim-zhao/battlemaniacs-restoration#5]
Our musician is busy...

**Comment by AlWesker** [comment]
S T ★ R (now known as Motavian Raider) told me he's moving along well with his commissions and intending to come back as quickly as a he can. Let's hope it's soon.

**Comment by AlWesker** [comment]
S T ★ R (now known as Motavian Raider) told me he's moving along well and intending to come back as quickly as a he can. Let's hope it's soon.

**Comment by maxim-zhao** [comment]
Are we going to get music for places where the title screen music is used currently, or there is silence? I can think of the game over screen, intermissions, credits.

**Comment by AlWesker** [comment]
Good point. I was actually thinking in this aspect.

I think the best with the intermissions and the game over screens is mimicking the SNES pattern. Both of these screens use the same music which is one still not composed for the Master System version though, titled "T. Bird". See how the SNES version works in that regard.

Intermission (see 9:45)

https://www.youtube.com/watch?v=WjzP6u6ayjc

Continuing the game (see 10:17)

https://www.youtube.com/watch?v=U8zamvkZnW8

Getting a Game Over

https://www.youtube.com/watch?v=SLZS3fUg06g

The only exception is the last intermission and the ending itself, which is still not implemented in the Master System version. In these two cases, the SNES version use a theme called "Victory" which is still not composed for the Master System either. The last intermission starts playing that theme and it continues straight to the ending with no music interruption.

Last Intermission + Ending

https://www.youtube.com/watch?v=gDC78GTwVLA

As for the Game Complete screen and the Credits, which are specific of the Master System version and not present in the SNES version, I suppose those will be coming after the ending when this one gets implemented. Right now, you have the last intermission which moves in to the Game Complete screen and then the Credits. When the ending is in place, I suppose the last intermission will move to the ending, then to the Game Complete screen and then the Credits.

In this case, we would have to discuss what we would be using for those Master System exclusive screens. I feel inclined to keep the "Victory" music from the last intermission and ending still playing on those screens, though. Or at least in the Game Complete screen one. With the credits, we would have to think in either let the music playing (which I prefer) or make it silent.

The title screen music itself, I would just leave it for the pre-title screens, the title screen itself, the intro and the selection screen. like the SNES version does. I wouldn't move it from there, despite the fact that the Master System version originally used that for the Game Over and Game Complete screens too.

**Comment by PyronsLair** [comment]
The ideal is remake all the musics if possible..
The newer music from turbo done its so very well done that's make the
others muscis sounds misplaced or from the toher console. I know that it
may be very hard.. but if possible,, it will be very good

2018-08-09 12:24 GMT-03:00 Albert Wesker <notifications@github.com>:

**Comment by AlWesker** [comment]
That depends on Motavian Raider willingness and opinion. We would have to wait for him to return from his busy schedule to see what the thinks about that matter. Nevertheless, the priority would be to do the four remaining uncomposed tracks ("Roller Coaster", "Bonus Level 2", "T. Bird" and "Victory"), or five if we include an unused track of the SNES version I'm not sure if we could use somehow.

https://www.youtube.com/watch?v=msyE-snguS0

**Comment by AlWesker** [comment]
Great news. Motavian Raider just confirmed me he's now available to resume doing the rest of the tracks. So I'm removing the "help wanted" tag and replacing it with "enhancement".

**Comment by AlWesker** [comment]
"Roller Coaster" track composed and uploaded. It sounds awesome, by the way.

**Comment by PyronsLair** [comment]
Where I can hear it?

Em seg, 13 de ago de 2018 19:03, Albert Wesker <notifications@github.com>
escreveu:

**Comment by AlWesker** [comment]
https://github.com/maxim-zhao/battlemaniacs-restoration/tree/master/src/vgms/music

You sure are going to like it. Motavian Raider did magic with it.

**Comment by AlWesker** [comment]
@MotavianRaider uploaded Bonus Stage 2 some days ago. I was outside home so couldn't have a listen until now. It's excellent as always, well done!

**Comment by AlWesker** [comment]
Ok, some bad news and some good news.

The bad news are that @MotavianRaider has stepped out of the project for reasons of his own. But the good news is that David Bonus (https://twitter.com/davidbonus), who has expertise and a career record composing music for systems like the Master System and the Mega Drive, is willing to do the remaining tracks, so he's welcome to the team. He has already do a v1 version (as he intends to do some refinement to it later on) of the T. Bird track, which is the one that goes both in the intermission screens and the continue/game over screens. He will also do the remaining tracks in his spare time, like the Victory (ending track) and any other that may be necessary. 

@maxim-zhao could you check if the T. Bird v1.vgm track which I uploaded suits well to the game? He composed it using PSG2Mod while keeping the 50hz norm and also looping the track, and he assumes it should be right with PSGLib, but you have to check it just to make sure.

**Comment by maxim-zhao** [comment]
I'm closing this as (1) we have a musician and (2) I'm getting confused by having multiple music threads to follow. Go to #15 for music discussion.
