### ISSUE TITLE
Corrupted intro graphics on Master System and Game Gear hardware

### ISSUE THREAD

**Issue by AlWesker** [maxim-zhao/battlemaniacs-restoration#8]
Only emulators and Mega Drive hardware are currently handling the new intro graphics well. Master System (at least a Japanese Master System 1) and Game Gear show corrupted/garbled graphics. This seems to be related to the speed at which the graphics are loaded.

**Comment by maxim-zhao** [comment]
Should be fixed on the latest version, can you test it?

**Comment by AlWesker** [comment]
Yeah. The scenes are now displayed perfectly both on Master System and Game Gear hardware. Well done!
